# Generated by Django 4.2.20 on 2025-04-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15)),
                ('element_type', models.CharField(max_length=15)),
                ('value_type', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'form_element',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=15)),
                ('value', models.JSONField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('sortable', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.form')),
                ('form_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.formelement')),
            ],
            options={
                'db_table': 'form_field',
            },
        ),
    ]
