# Generated by Django 4.2.20 on 2025-04-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='value',
            new_name='values',
        ),
    ]
